import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateContaDto } from './dto/create-contas.dto';
import { UpdateContaDto } from './dto/update-contas.dto';

@Injectable()
export class ContasService {
  constructor(private readonly prisma: PrismaService) {}

  create(dto: CreateContaDto) {
    // Exclude idConta if it should be auto-generated by the database
    return this.prisma.conta.create({ data: dto });
  }

  findAll() {
    return this.prisma.conta.findMany({
      include: { usuario: true, grupo: true },
    });
  }

  async findOne(id: number) {
    const conta = await this.prisma.conta.findFirst({
      where: { idConta: id },
      include: { usuario: true, grupo: true },
    });

    if (!conta) throw new NotFoundException('Conta não encontrada');
    return conta;
  }

  update(id: number, dto: UpdateContaDto & { idUsuario: number }) {
    return this.prisma.conta.update({
      where: { idConta_idUsuario: { idConta: id, idUsuario: dto.idUsuario } },
      data: dto,
    });
  }

  remove(id: number, idUsuario: number) {
    return this.prisma.conta.delete({
      where: { idConta_idUsuario: { idConta: id, idUsuario } },
    });
  }
}
